- hosts: fresh-raspberrypi
  remote_user: pi
  become: True
  become_method: sudo
  gather_facts: True

  vars:
#   admin_user: rhempel
#   admin_user_key: https://github.com/rhempel.keys
#   host: fartplan
#   interface: wlan0
#   ipaddress: 169.254.240.247
#   routers: 10.88.111.254
#   dns_servers: 10.88.111.1
    SSH: True
    REBOOT: True
    LOCALE: "en_DK.UTF-8"
    TIMEZONE: "Europe/Copenhagen"
    XKBLAYOUT: "us"
    WIFI_COUNTRY: "US"

  roles:
  - rpi.configure_wifi
# - rhempel.user_setup

# tasks:
# - name: Just let the world know this kind of works
#   block:
#   - command: echo "Hello World from {{ ansible_host }}"


    # - name: Include the WiFI setup play
    #   vars:
    #     remote_user: pi
    #   import_playbook: wifi/agersnapsvej.yml


# rh #Get some basic info
# rh   - name: Get Raspberry Pi type
# rh     shell: "raspi-config nonint get_pi_type"
# rh     register: pi_type
# rh     changed_when: False
# rh 
# rh   - name: Show pi version
# rh     debug:
# rh        msg: "Pi version: {{ pi_type.stdout }}"
# rh 
# rh #1 Change user password
# rh 
# rh     # ansible-vault and user module ??
# rh     #- name: Change user password
# rh     #shell: "(echo '{{ NEWPASSWORD }}' ; echo '{{ NEWPASSWORD }}') | passwd {{ USER }}"
# rh 
# rh #2 Network Options
# rh 
# rh     #N1 Hostname
# rh   - name: Get hostname
# rh     shell: "raspi-config nonint get_hostname"
# rh     register: pi_hostname
# rh     changed_when: False
# rh 
# rh   - name: Print current hostname
# rh     debug:
# rh       msg: "Current hostname: {{ pi_hostname.stdout }}"
# rh 
# rh # - name: Change hostname
# rh #   shell: "raspi-config nonint do_hostname {{ HOSTNAME }}"
# rh #   when: pi_hostname.stdout != HOSTNAME
# rh 
# rh     #N2 Wi-fi
# rh     #- name: Set WiFi credentials
# rh       #shell: "raspi-config nonint do_wifi_ssid_passphrase {{ SSID }} {{ PASSPHRASE }}"
# rh       #
# rh       #
# rh # SSH Tasks
# rh   - name: Check if SSH is enabled or not
# rh     shell: "raspi-config nonint get_ssh"
# rh     register: ssh_status
# rh     changed_when: False
# rh 
# rh   - name: Print SSH status
# rh     debug: 
# rh       msg: "SSH status is: {{ ssh_status.stdout }}"
# rh 
# rh   - name: Enable SSH
# rh     shell: "raspi-config nonint do_ssh 0"
# rh     when: (SSH == True) and (ssh_status.stdout != '0')
# rh 
# rh   - name: Disable SSH
# rh     shell: "raspi-config nonint do_ssh 1"
# rh     when: (SSH == False) and (ssh_status.stdout != '1')
# rh 
# rh #4 Localisation Options
# rh 
# rh   #I1 Change Locale
# rh   - name: Change locale
# rh     shell: "raspi-config nonint do_change_locale {{ LOCALE }}"
# rh 
# rh   #I2 Change Timezone
# rh   - name: Change timezone
# rh     shell: "raspi-config nonint do_change_timezone {{ TIMEZONE }}"
# rh 
# rh   #I3 Change Keyboard Layout
# rh   - name: Change keyboard layout
# rh     shell: "raspi-config nonint do_configure_keyboard {{ XKBLAYOUT }}"
# rh 
# rh   #I4 Change Wi-fi Country
# rh   - name: Get WiFi country
# rh     shell: "raspi-config nonint get_wifi_country"
# rh     register: wifi_country
# rh     changed_when: False
# rh     ignore_errors: True #to avoid error when WiFi is not present
# rh 
# rh   - name: Print current WiFi country
# rh     debug: 
# rh       msg: "Wifi country is: {{ wifi_country.stdout }}" 
# rh 
# rh   - name: Set WiFi country
# rh     shell: "raspi-config nonint do_wifi_country {{ WIFI_COUNTRY }}"
# rh 
# rh # - name: Update all packages to latest within distro, then remove unneeded
# rh #   block:
# rh #     - apt: update_cache=yes upgrade=dist
# rh #     - apt: autoremove=yes
# rh #
# rh


