- hosts: all
  become: True
  become_method: sudo
  gather_facts: True

# The vars section here should be set to reasonable defaults in the
# corresponding hosts file
  vars:
    ansible_user: pi
    ssh: True
    wifi: True
    poweroff: False

  roles:
  - rpi.configure_ssh
  - rpi.configure_wifi

  # Delay poweroff for one minute to allow hostname to change
  #
  # If poweroff is False then just restart - do not poweroff

  - rpi.poweroff
  - rpi.configure_hostname
