- hosts: fresh_raspberrypi
  become: True
  become_method: sudo
  gather_facts: True

# The vars section here should be set to reasonable defaults in the
# corresponding hosts file
  vars:
        ssh: True
        wifi: True
        poweroff: True
        ansible_user: pi

  roles:
  - rpi.configure_ssh
  - rpi.configure_wifi
  - rpi.configure_hostname
  - rpi.poweroff
