# rpi.configure-ssh - Enables or disables ssh based on ssh variable
---
  - name: Check if SSH is enabled or not
    shell: "systemctl is-enabled ssh"
    register: ssh_status
    changed_when: False
    failed_when: "ssh_status.rc not in [ 0, 1 ]"

  - name: Print SSH status
    debug: 
      msg: "SSH status is: {{ ssh_status.stdout }}"

  - name: Enable SSH
    shell: "systemctl enable ssh"
    when: (ssh == True) and (ssh_status.stdout == "disabled")
    changed_when: True

  - name: Disable SSH
    shell: "systemctl disable ssh"
    when: (ssh == False) and (ssh_status.stdout == "enabled")
    changed_when: True
