# rpi.configure-ssh - Enables or disables ssh based on ssh variable
---
  - name: Enable SSH
    shell: "raspi-config nonint do_ssh 0"
    when: (ssh == True)
    changed_when: False

  - name: Disable SSH
    shell: "raspi-config nonint do_ssh 1"
    when: (ssh == False)
    changed_when: False

  - name: Check if SSH is enabled or not
    shell: "raspi-config nonint get_ssh"
    register: ssh_status
    changed_when: False

  - name: Print SSH status
    debug: 
      msg: "SSH status is: {{ ssh_status.stdout }}"
