# rpi.poweroff - Powers off the pi if configured to do so
---
  - name: Poweroff if enabled
    become: yes
    shell: "shutdown -h now"
    register: poweroff_status
    failed_when: "poweroff_status.rc not in [ 0 ]"
    when: (poweroff == True)
