# Update and upgrade all packages using apt-get then cleanup
---
- name: Update all packages to latest within distro, then remove unneeded
  block:
    - apt:
          update_cache: yes
          upgrade: dist
          cache_valid_time: 7200
    - apt:
          autoremove: yes
