# rpi.configure_hostname - Sets the new hostname if specified
---
- name: Get hostname
  shell: "hostnamectl --static status"
  register: pi_hostname
  changed_when: False

- name: Print current hostname
  debug:
    msg:
    - "Current hostname: {{ pi_hostname.stdout }}"
    - "New hostname: {{ hostname }}"

- name: Change hostname
  shell: "hostnamectl --static set-hostname {{ hostname }}"
  when: (pi_hostname.stdout != hostname)

- name: Ensure hostname is in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regex: '127\.0\.1\.1\s*{{ pi_hostname.stdout }}'
    line: '127.0.0.1	{{ hostname }}'
    owner: root
    group: root
    mode: '0644'
